//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Napelemrendszer.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        public int ID { get; set; }
        public int StorageID { get; set; }
        public int RequiredQuantity { get; set; }
    }
}
