//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Napelemrendszer.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progress
    {
        public int ID { get; set; }
        public int ProjectID { get; set; }
        public System.DateTime New { get; set; }
        public Nullable<System.DateTime> Draft { get; set; }
        public Nullable<System.DateTime> Wait { get; set; }
        public Nullable<System.DateTime> Scheduled { get; set; }
        public Nullable<System.DateTime> InProgress { get; set; }
        public Nullable<System.DateTime> Completed { get; set; }
        public Nullable<System.DateTime> Failed { get; set; }
    }
}
