//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Napelemrendszer.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projet
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public int ProgressID { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public Nullable<int> ComponentsID { get; set; }
        public Nullable<int> WorkPrice { get; set; }
        public Nullable<int> FullPrice { get; set; }
        public Nullable<int> RequiredTime { get; set; }
    }
}
