//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Napelemrendszer.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        public int ID { get; set; }
        public int Row { get; set; }
        public int Column { get; set; }
        public int Shelf { get; set; }
        public int Cell { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> MaxQuantity { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Reserved { get; set; }
    }
}
